export const initialState = {
  appname: '',
  description: '',
  version: '0.1.0',
  typescript: false,
  prettier: false,
  flow: false,
  tailwind: false,
  bootstrap: false,
  reactbootstrap: false,
  materialui: false,
  styledcomponents: false,
  normalize: false,
  reactrouter: false,
  proptypes: false,
  sourcemapexplorer: false,
  storybook: false,
};

export const initialStateVite = {
  appname: '',
  description: '',
  version: '0.1.0',
  typescript: false,
  prettier: false,
  flow: false,
  tailwind: false,
  bootstrap: false,
  materialui: false,
  reactbootstrap: false,
  normalize: false,
  reactrouter: false,
  proptypes: false,
  sourcemapexplorer: false,
};